   version: '3.8'
   services:
     app:
       build: .
       environment:
         DB_HOST: postgres
         DB_PORT: 5432
         DB_USERNAME: postgres
         DB_PASSWORD: postgres
         DB_NAME: wms
       depends_on:
         - postgres
       networks:
         - app-network

     postgres:
       image: postgres:latest
       container_name: wms_postgres
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: wms
       ports:
         - "5432:5432"
       volumes:
         - postgres_data:/var/lib/postgresql/data
       networks:
         - app-network

   volumes:
     postgres_data:

   networks:
     app-network: